# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Insira o enunciado da reda\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Insira o t\xedtulo da sua prova')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('exam_list', 'Can see exam list'), ('exam_detail', 'Can see exam detail')),
            },
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Insira o t\xedtulo do novo template de prova')),
                ('questions', models.IntegerField(verbose_name='Insira a quantidade de quest\xf5es')),
                ('answers', models.IntegerField(verbose_name='Insira a quantidade de alternativas')),
                ('essay', models.BooleanField(verbose_name='Marcar caso deseja incluir reda\xe7\xe3o a esse template')),
            ],
            options={
                'permissions': (('exam_template_list', 'Can see template list'), ('exam_template_detail', 'Can see template detail')),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', tinymce.models.HTMLField(verbose_name='Insira o texto da alternativa sem a letra')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Insira o enunciado da quest\xe3o sem a sua numera\xe7\xe3o')),
                ('sequence', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Exam')),
            ],
            options={
                'permissions': (('question_list', 'Can see question list'), ('question_detail', 'Can see question detail')),
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ExamTemplate', verbose_name='Escolha o modelo de template que ser\xe1 usado na sua prova'),
        ),
        migrations.AddField(
            model_name='essay',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Exam'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
